//This file contains helper functions that are used in App.jsx
import { uniqueNamesGenerator, adjectives, colors, animals } from 'unique-names-generator';

/* Sends post requests to the server using fetch. Will look for various
   entries in the response JSON object, and will handle them appropriately.
*/
const sendPost = async (url, data) => {

    const response = await fetch(url, {
        method: 'POST',
        headers: {
            'Content-Type': 'application/json',
        },
        body: JSON.stringify(data),
    });

    const result = await response.json();

    if (handler) {
        handler(result);
    }
};

/**
 * 
 * @returns a random name generated by the unique-names-generator library
 */
const generateUniqueName = () => {
    let randomName = uniqueNamesGenerator({ dictionaries: [adjectives, colors, animals] });
    console.log(randomName);
    return randomName;
};

// Function to generate a unique key. This allows each constellation to have a unique identity
const generateUniqueKey = () => {
    return Math.random().toString(36).substr(2, 9);
};

//export the functions so they can be used in App.jsx
export { sendPost, generateUniqueName, generateUniqueKey };