/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 Avocado.glb --transform 
Files: Avocado.glb [8.33MB] > /Users/reese/Downloads/Avocado-transformed.glb [226.43KB] (97%)
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";


export default function Avocado(props) {
  const { nodes, materials } = useGLTF('/Avocado-transformed.glb')
  const groupRef = useRef()

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.015;
  });

  return (
    // <group ref={groupRef} {...props} dispose={null}>
    <group ref={groupRef} {...props} dispose={null}>
      <mesh geometry={nodes.Avocado.geometry} material={materials['2256_Avocado_d']} rotation={[-Math.PI, 0, -Math.PI]} />
    </group>
  )
}

useGLTF.preload('/Avocado-transformed.glb')
