/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 fireplanetFINAL.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function FirePlanet(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/fireplanetFINAL.glb')

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.015;
  });

  return (
    <group {...props} ref={groupRef} position={[-10, 3, 15]} dispose={null}>
      <mesh geometry={nodes.Planet.geometry} material={materials.Lava} />
      <mesh geometry={nodes.Atmosphere.geometry} material={materials.Clouds} scale={1.036} />
    </group>
  )
}

useGLTF.preload('/fireplanetFINAL.glb')
