/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 gasgiant.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";

export default function GasGiant(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/gasgiant_glow.glb')

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.02;
  });

  return (
    <group {...props} ref={groupRef} position={[-45, 30, 45]} scale={[10, 10, 10]} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
    </group>
  )
}

useGLTF.preload('/gasgiant_glow.glb')
