/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 iceplanet.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";


export default function IcePlanet(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/waterplanet_glow.glb')

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.01;
  });

  return (
    <group {...props} ref={groupRef} position={[5, 0, 10]}  dispose={null}>
      <mesh geometry={nodes.Planet.geometry} material={materials['Water Material']} />
    </group>
  )
}

useGLTF.preload('/waterplanet_glow.glb')