/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 iceplanet.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber";


export default function IcePlanet(props) {
  const groupRef = useRef()
  const { nodes, materials } = useGLTF('/public/iceplanet.glb')

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.01;
  });

  return (
    <group {...props} ref={groupRef} position={[3, 2, 0]} dispose={null}>
      <mesh geometry={nodes.Icosphere.geometry} material={materials.Ice} />
    </group>
  )
}

useGLTF.preload('/iceplanet.glb')
