/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 rockplanet.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function RockPlanet(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/rockplanet_glow.glb");

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.0005;
  });

  return (
    <group {...props} ref={groupRef} position={[4, -5, 15]} dispose={null}>
      <mesh geometry={nodes.Planet.geometry} material={materials.Rock} />
    </group>
  );
}

useGLTF.preload("/rockplanet_glow.glb");
