/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 waterplanet_glow.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function WaterPlanet(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/waterplanet_glow.glb");

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.0015;
  });
  return (
    <group
      {...props}
      ref={groupRef}
      position={[45, 50, 40]}
      scale={[9, 9, 9]}
      dispose={null}
    >
      <mesh
        geometry={nodes.Planet.geometry}
        material={materials["Water Material"]}
      />
    </group>
  );
}

useGLTF.preload("/waterplanet_glow.glb");
