/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 whiteplanet_glow.glb 
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";

export default function WhitePlanet(props) {
  const groupRef = useRef();
  const { nodes, materials } = useGLTF("/whiteplanet_glow.glb");

  useFrame(({ clock }) => {
    // Rotate the mesh around the Y axis
    const elapsedTime = clock.getElapsedTime();
    //orbit the location [0,0,0]
    groupRef.current.rotation.y += 0.003;
  });
  return (
    <group
      {...props}
      ref={groupRef}
      position={[15, 10, -60]}
      scale={[9, 9, 9]}
      dispose={null}
    >
      <mesh
        geometry={nodes.Sphere.geometry}
        material={materials["Material.001"]}
      />
    </group>
  );
}

useGLTF.preload("/whiteplanet_glow.glb");
